### PR TITLE
Add a simple asciidoctor ietf converter

### PR DESCRIPTION
**Pull request by abunashir**
This pull request adds a basic starting point for gem version 2.0, this includes converting the metadata from an ietf asciidoc documents, and this also updates some configuration so we only run our test suite only to this recent changes.

### CODE REVIEW

**Comment by abunashir** [comment]
Hi @ronaldtse, @opoudjis I was trying to work on this one, but still feels like I'm missing the big picture, it seems to be generating the interemediary document, but I'm still not sure about most of the stuff and if that's the correct one and also getting lots of warning about the validations and everything.

Would any of you guys be avaiable for a quick chat sometime next week and help me understand the missing part?

**Comment by opoudjis** [comment]
This week probably not, next week probably yes. I have a 15 Jan deadline for Ronald.

**Comment by ronaldtse** [comment]
@abunashir yes we have a deadline upcoming, but at its base:

1. https://github.com/riboseinc/metanorma-model-standoc ("StanDoc") is a document model for "standardization documents". A "standardization document" is a "standard" like ISO standards, IETF standards, etc.

2. https://github.com/riboseinc/metanorma-standoc is the document "processor" that implements the StanDoc model. All our Metanorma processor gems inherit from it, including Metanorma-ISO, Metanorma-CSD, etc. The only one that doesn't is Metanorma-IETF.

(will update this when I have time...)

**Comment by abunashir** [comment]
Cool, thanks guys, I'm actually going through those along with the iso processor. It's taking quite some time to get my head around through this standard that's why I thought it might save some time having a quick chat.

But no worries, I will dig dipper and let me know when you guys have time 👍

**Comment by abunashir** [comment]
@ronaldtse: As you mentioned in a separate issue, the author data are the only one which is different, so I'am those under the contributor node, please let me know if that's okay or if you would have prefered otherwise :)

screenshot 2019-01-08 18 18 11

**Comment by opoudjis** [comment]
Yes, the encoding looks reasonable.

I am in the UK for the next month; I will need notice to have a chat, but it can be done.

The Metanorma XML spec is indeed defined in https://github.com/riboseinc/metanorma-model-standoc, and is the intermediate format for specs. Basically, it's meant to be an Asciidoctor-friendly model of text: it divides documents structure into sections, blocks (paragraph-level), and inline markup. The inline markup is pretty much HTML. The block markup is the recurring elements which show up in standards, including examples, notes, figures, sourcecode, etc. 

The target output is normally HTML or Word HTML; you are being dumped with the completely novel work of mapping Metanorma XML to RFC2XML, as a child of the Isodoc gem. I did a partial mapping in https://github.com/riboseinc/ietfbib/issues/1, but that's only really at the inline level, and in the context of bibliographic markup. On the plus side, the mapping work won't be as fiddly as for HTML, since you are mapping abstract container classes to abstract container classes, instead of renderables. On the minus side, this mapping is to be done completely from scratch, with your only guidance the https://tools.ietf.org/html/rfc7749 spec. (Don't bother with https://tools.ietf.org/html/rfc7991 in the first instance; it is in fact much closer in some ways to HTML and Metanorma XML, but it is also not yet in use.)

**Comment by opoudjis** [comment]
Warnings: they turn out to be long undetected errors in generation which contradict the prescribed grammar; I have been fixing them now mainly in standoc.

**Comment by opoudjis** [comment]
Only a few are your errors. Note that initial in the grammar precedes surname -- and that they are meant to be mutually exclusive with completename (I'm relaxing that.) Note also that the Relaton address element currently does not use region but state. And contact is a switch, not an element.

**Comment by abunashir** [comment]
Amazing @opoudjis, you saved me lots of time, thanks a lot :)

**Comment by opoudjis** [comment]
I may have saved you some time now, but this is going to be a very big task :(

**Comment by abunashir** [comment]
That's what I figured, I'm just trying to get my head around this and once I get a hold of it then I hope it should be easier 🤞🤞🤞

**Pull request merged**
